[package]
name = "const-gen-derive"
version = "0.1.0"
authors = ["Griffin O'Neill <gsoneill1003@gmail.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
syn = "1.0"
quote = "1.0"
proc-macro2 = "1.0"

